add_newline = false
format = "$sudo$directory$git_branch$character"

[directory]
truncation_length = 2
truncate_to_repo = true

[git_branch]
symbol = ""
format = "[$branch]($style) "

[sudo]
disabled = false
symbol = "sudo"
format = "[$symbol]($style) "
style = "bold red"

[character]
success_symbol = '\$'
error_symbol = '\$'
vimcmd_symbol = '\$'
