theme = "onedark"

# Open Yazi and open selected file in Helix
[keys.normal.space]
e = [
  # Remove previous selection file
  ':sh rm -f /tmp/yazi-chooser',

  # Launch Yazi and store selected path
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-chooser',

  # Restore terminal state after Yazi exits
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',

  # Open selected file in Helix
  ':open %sh{cat /tmp/yazi-chooser}',

  # Refresh UI
  ':redraw',
]
